// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExpense(arg1, arg2, arg3) {
  return window['go']['service']['DataService']['AddExpense'](arg1, arg2, arg3);
}

export function AddIncome(arg1, arg2, arg3) {
  return window['go']['service']['DataService']['AddIncome'](arg1, arg2, arg3);
}

export function Close() {
  return window['go']['service']['DataService']['Close']();
}

export function CreateProject(arg1) {
  return window['go']['service']['DataService']['CreateProject'](arg1);
}

export function ListExpenses(arg1) {
  return window['go']['service']['DataService']['ListExpenses'](arg1);
}

export function ListIncomes(arg1) {
  return window['go']['service']['DataService']['ListIncomes'](arg1);
}
