// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function AddExpense(arg1:number,arg2:string,arg3:number):Promise<data.Expense>;

export function AddIncome(arg1:number,arg2:string,arg3:number):Promise<data.Income>;

export function Close():Promise<void>;

export function CreateProject(arg1:string):Promise<data.Project>;

export function ListExpenses(arg1:number):Promise<Array<data.Expense>>;

export function ListIncomes(arg1:number):Promise<Array<data.Income>>;
