// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window.go.service.DataService.CreateProject(arg1);
}

export function ListProjects() {
  return window.go.service.DataService.ListProjects();
}

export function GetProject(arg1) {
  return window.go.service.DataService.GetProject(arg1);
}

export function UpdateProject(arg1, arg2) {
  return window.go.service.DataService.UpdateProject(arg1, arg2);
}

export function DeleteProject(arg1) {
  return window.go.service.DataService.DeleteProject(arg1);
}

export function AddExpense(arg1, arg2, arg3) {
  return window.go.service.DataService.AddExpense(arg1, arg2, arg3);
}

export function UpdateExpense(arg1, arg2, arg3, arg4) {
  return window.go.service.DataService.UpdateExpense(arg1, arg2, arg3, arg4);
}

export function DeleteExpense(arg1) {
  return window.go.service.DataService.DeleteExpense(arg1);
}

export function ListExpenses(arg1) {
  return window.go.service.DataService.ListExpenses(arg1);
}

export function AddIncome(arg1, arg2, arg3) {
  return window.go.service.DataService.AddIncome(arg1, arg2, arg3);
}

export function UpdateIncome(arg1, arg2, arg3, arg4) {
  return window.go.service.DataService.UpdateIncome(arg1, arg2, arg3, arg4);
}

export function DeleteIncome(arg1) {
  return window.go.service.DataService.DeleteIncome(arg1);
}

export function ListIncomes(arg1) {
  return window.go.service.DataService.ListIncomes(arg1);
}

export function CalculateProjectTaxes(arg1, arg2) {
  return window.go.service.DataService.CalculateProjectTaxes(arg1, arg2);
}
