// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExpense(arg1, arg2) {
  return window.go.service.DataService.AddExpense(arg1, arg2);
}

export function ListExpenses() {
  return window.go.service.DataService.ListExpenses();
}

export function AddIncome(arg1, arg2) {
  return window.go.service.DataService.AddIncome(arg1, arg2);
}

export function ListIncomes() {
  return window.go.service.DataService.ListIncomes();
}
