// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {context} from '../models';

export function AddExpense(projectID:number,category:string,amount:number):Promise<data.Expense>;

export function ListExpenses(projectID:number):Promise<Array<data.Expense>>;
