// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {context} from '../models';

export function AddExpense(arg1:string,arg2:number):Promise<void>;

export function ListExpenses():Promise<Array<data.Expense>>;

export function Startup(arg1:context.Context):Promise<void>;
