name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend deps
        run: npm ci --prefix internal/ui

      - name: Lint frontend
        run: npm run lint --prefix internal/ui

      - name: Run frontend tests
        run: npm test --prefix internal/ui

      - name: Go vet
        run: go vet ./cmd/... ./internal/... ./internal/pdf/...

      - name: Go tests
        run: go test ./cmd/... ./internal/... ./internal/pdf/...
